module.exports = {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.ts',
    ],
    theme: {
        extend: {
            colors: {
                'surface-variant': '#d9e3f6',
                'on-secondary-fixed': '#00164e',
                'primary-container': '#10b981',
                outline: '#6c7a71',
                'error-container': '#ffdad6',
                'on-tertiary': '#ffffff',
                'on-primary-container': '#00422b',
                'surface-container': '#e6eeff',
                'surface-bright': '#f8f9ff',
                'primary-fixed': '#6ffbbe',
                'secondary-container': '#8fa7fe',
                'surface-tint': '#006c49',
                'on-surface': '#121c2a',
                'on-surface-variant': '#3c4a42',
                'secondary-fixed': '#dce1ff',
                'on-tertiary-container': '#523200',
                'on-secondary-fixed-variant': '#264191',
                tertiary: '#855300',
                'on-background': '#121c2a',
                'on-error': '#ffffff',
                surface: '#f8f9ff',
                'tertiary-fixed-dim': '#ffb95f',
                'inverse-surface': '#27313f',
                'tertiary-fixed': '#ffddb8',
                'tertiary-container': '#e29100',
                background: '#f8f9ff',
                'primary-fixed-dim': '#4edea3',
                secondary: '#4059aa',
                'on-tertiary-fixed-variant': '#653e00',
                'outline-variant': '#bbcabf',
                'surface-container-low': '#eff4ff',
                'surface-container-highest': '#d9e3f6',
                'on-primary-fixed': '#002113',
                'surface-container-lowest': '#ffffff',
                'surface-dim': '#d0dbed',
                'on-primary-fixed-variant': '#005236',
                'on-primary': '#ffffff',
                'on-secondary-container': '#1d3989',
                'secondary-fixed-dim': '#b6c4ff',
                'inverse-on-surface': '#eaf1ff',
                error: '#ba1a1a',
                'on-error-container': '#93000a',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                lg: '32px',
                gutter: '24px',
                xs: '8px',
                md: '24px',
                base: '4px',
                xl: '48px',
                'margin-desktop': '32px',
                sm: '16px',
                'margin-mobile': '16px',
            },
            fontFamily: {
                'body-md': ['Inter'],
                'headline-lg': ['Inter'],
                'label-md': ['Inter'],
                'headline-sm': ['Inter'],
                'headline-md': ['Inter'],
                'body-lg': ['Inter'],
                'display-lg': ['Inter'],
                'body-sm': ['Inter'],
                'label-sm': ['Inter'],
            },
            fontSize: {
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
            },
        },
    },
};
